gui: fix some weird syntax errors on Windows
```
:\projects\familyline\src\include\client/graphical/gui/gui_box.hpp(91,13): error C3646: 'previous_tab_index_': unknown override specifier [C:\projects\familyline\build\src\client\familyline-client.vcxproj]
C:\projects\familyline\src\include\client/graphical/gui/gui_box.hpp(91,33): error C2059: syntax error: '=' [C:\projects\familyline\build\src\client\familyline-client.vcxproj]
C:\projects\familyline\src\include\client/graphical/gui/gui_box.hpp(91,37): error C2238: unexpected token(s) preceding ';' [C:\projects\familyline\build\src\client\familyline-client.vcxproj]
C:\projects\familyline\src\include\client/graphical/gui/gui_box.hpp(92,13): error C3646: 'tab_index_': unknown override specifier [C:\projects\familyline\build\src\client\familyline-client.vcxproj]
C:\projects\familyline\src\include\client/graphical/gui/gui_box.hpp(92,33): error C2059: syntax error: '=' [C:\projects\familyline\build\src\client\familyline-client.vcxproj]
C:\projects\familyline\src\include\client/graphical/gui/gui_box.hpp(92,37):
error C2238: unexpected token(s) preceding ';'
[C:\projects\familyline\build\src\client\familyline-client.vcxproj]

...

```

Those quoted errors might be caused by a missing ssize_t definition